include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - lib/firebase_options.dart
    - "**.freezed.dart"
    - "**.g.dart"

linter:
  rules:
    flutter_style_todos: false
    public_member_api_docs: false
