name: crea_chess
description: A prototype for Chess World, a chess variants app.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  badges: ^3.1.2
  chessground: ^2.1.0
  cloud_firestore: ^4.13.1
  collection: ^1.17.2
  cupertino_icons: ^1.0.2
  dartchess_webok: ^0.1.0
  diacritic: ^0.1.4
  fast_immutable_collections: ^9.1.6
  firebase_app_check: ^0.2.1+6
  firebase_auth: ^4.12.1
  firebase_core: ^2.21.0
  firebase_database: ^10.3.3
  firebase_storage: ^11.5.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_login_facebook: ^1.9.0
  formz: ^0.6.1
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^12.1.1
  google_sign_in: ^6.1.5
  hydrated_bloc: ^9.1.2
  image_picker: ^1.0.4
  intl: ^0.18.1
  json_annotation: ^4.8.1
  path_provider: ^2.1.1
  regexpattern: ^2.6.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/avatar/
    - assets/banner/
    - assets/icon/
    - assets/piece_sets/frenzy/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/crea_chess_icon_v1.png"
